name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [amd64, arm]
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Build
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: go build -o exec-in-net_${{ matrix.goos }}_${{ matrix.goarch }} .

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exec-in-net_${{ matrix.goos }}_${{ matrix.goarch }}
          path: exec-in-net_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
